---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# famexploreR

<!-- badges: start -->
[![Project Status: Active – The project has reached a stable, usable
state and is being actively
developed.](https://www.repostatus.org/badges/latest/active.svg)](https://www.repostatus.org/#active)
[![License: GPL
v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)
<!-- badges: end -->

El objetivo de `famexploreR` es poder importar datos de estadillos de campo de seguimiento de Flora Amenezada y realizar sobre ellos diferentes cálculos y gráficos para generar informes. 

## Instalación 

Puedes instalar la versión de desarrollo de famexploreR desde GitHub con el siguiente código:

``` r
# install.packages("devtools")
devtools::install_github("ajpelu/famexploreR")
```

**famexploreR** fue construido en [R](https://www.r-project.org), un lenguaje de programación de código abierto, utilizando el paquete [Shiny](https://shiny.rstudio.com), un marco de aplicación web para R.

Puedes descargar la versión de desarrollo de **famexploreR** desde [GitHub](https://github.com/ajpelu/famexploreR).


## Cómo ejecutar famexploreR

La opción recomendada para utilizar la aplicación es descargar el paquete y ejecutarlo localmente. 

### Localmente

1. Se recomienda el uso de Rstudio.

2. Descarga e instala el paquete `famexploreR` usando:

``` r
# install.packages("devtools")
devtools::install_github("ajpelu/famexploreR")
```

3. Ejecuta la aplicación:

```r
library("famexploreR")
launch_famexplorer()
```

### Live 

También se puede instalar el paquete en un servidor que contenga R-studio y shiny. De forma provisional se muestra un ejemplo [aquí](http://vlab.iecolab.es/ajpelu/famexploreR/)

Todo el código necesario se encuentra en este [repositorio](https://github.com/ajpelu/famexploreR)

